# Generated by Django 5.2.9 on 2026-01-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=20)),
                ('dep', models.CharField(max_length=20)),
            ],
        ),
    ]
