# Generated by Django 5.2.9 on 2026-01-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('attendance', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
