# Generated by Django 5.2.9 on 2026-01-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_id_student_student_id_remove_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='risk',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
