# Generated by Django 5.2.9 on 2026-02-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_risk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='risk',
        ),
    ]
