# Generated by Django 5.2.9 on 2026-02-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='risk',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
