# Generated by Django 5.2.9 on 2026-03-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_subjectattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='alert_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SubjectAttendance',
        ),
    ]
