# Generated by Django 5.2.9 on 2026-03-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_counselling'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('IMPROVED', 'Improved'), ('CRITICAL', 'Critical')], default='ONGOING', max_length=20),
        ),
    ]
