# Generated by Django 5.2.9 on 2026-03-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
