# Generated by Django 5.2.9 on 2026-03-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_student_parent_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_phone',
        ),
    ]
